PACKAGE_NAME="ch9344"
PACKAGE_VERSION="1.9"
MAKE[0]="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build/driver CC=gcc-12"
CLEAN="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build/driver clean"
BUILT_MODULE_NAME[0]="ch9344"
BUILT_MODULE_LOCATION=driver/
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
